[tool.poetry]
name = "ambiente-virtual"
version = "0.1.0"
description = ""
authors = ["Dev-magno <magnolopes1212@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
